### ISSUE TITLE
Layout Problems on devices with different resolutions

### ISSUE THREAD

**Issue by mateicristina** [TeodoraIoanaJipa/MDSActivityApp#8]
Nu se vede bine pe unele deviceuri. Scrisul iese din ecran
![57444609_2671587786202940_2378053658706182144_n](https://user-images.githubusercontent.com/32592029/57621550-6c0e5900-7594-11e9-87a0-2a039bddcf9f.png)

**Comment by TeodoraIoanaJipa** [comment]
Am transformat layout'ul in ConstraintLayout. si am pus constraint stanga, drapta si sus!! Nu si jos pentru ca nu mai poate sa si ia heigth'ul pentru toate tipurile de device'uri
![61621902_299766034265512_3748544282244415488_n](https://user-images.githubusercontent.com/32644297/58428184-5d529680-80aa-11e9-84f2-1be8d4d82f88.png)
