### ISSUE TITLE
Landscape

### ISSUE THREAD

**Issue by TeodoraIoanaJipa** [TeodoraIoanaJipa/MDSActivityApp#9]
In landscape ode aplicatia nu arata chiar asa de bine
De exemplu StartMenu arata asa:
![61540306_291059278514831_7094411221297790976_n](https://user-images.githubusercontent.com/32644297/58428941-cb985880-80ac-11e9-9f00-cc85abd1c6bf.png)

**Comment by denisachicarosa** [comment]
Am rezolvat problema.
Am testat si acum se vede bine 
![61122493_678561985906546_8805696955628912640_n](https://user-images.githubusercontent.com/30755333/58467846-136abe80-8145-11e9-9729-5164e440440b.png)
